extends Node2D

# TODO:
# - add impulsing to demo loader, make sure the params get copied to there

# Notes:
# - changed act function to 4 outputs, changed params to use simoid

var time = 0
var total_time = 0
var time_step = 0.2
# each generation needs to pass n_trials, lasting trial_time.
var n_trials = 4
var cur_trial = 1
var trial_time = 15

var paused = true

var agent_body_path = "res://demos/impulsing/creature/Creature.tscn"
var ga: GeneticAlgorithm

var use_player = false
var creature_controller


func _ready():
    if use_player:
        var creature_to_control = load(agent_body_path).instance()
        creature_controller = load("res://demos/impulsing/creature/creature_controller.gd").new(creature_to_control)
        add_child(creature_controller)
        creature_controller.add_child(creature_to_control)
    else:
        ga = GeneticAlgorithm.new(4, 4, agent_body_path, true, "impulsing_params")
        add_child(ga)
        place_new_bodies(ga.get_curr_bodies())
        paused = false


func _physics_process(delta) -> void:
    # update time since last update
    if not paused:
        time += delta
        total_time += delta
        # next timestep
        if time > time_step:
            ga.next_timestep()
            time = 0
        # check next trial
        if total_time >= trial_time:
            total_time = 0
            cur_trial += 1
            # check enough trials
            if cur_trial > n_trials:
                # go to next generation
                cur_trial = 1
                ga.evaluate_generation()
                ga.next_generation()
                place_new_bodies(ga.get_curr_bodies())
            # else continue with next trial if not finished
            else:
                next_trial()


func place_new_bodies(bodies: Array) -> void:
    """Adds the bodies scenes generated by the ga to the tree, and removes the old ones.
    """
    # remove the bodies from the last generation
    for last_gen_body in $CreatureSpawn.get_children():
        last_gen_body.queue_free()
    # add the new bodies to the scene
    for body in bodies:
        $CreatureSpawn.add_child(body)


func next_trial() -> void:
    """
    """
    $Target.move_by_fraction(n_trials)
    for body in $CreatureSpawn.get_children():
        body.update_fitness()
        body.global_position = $CreatureSpawn.global_position